In [1]:
import numpy as np
import pandas as pd

In [2]:
def loading_txt(root, first_row, first_column):
    #read txt method one
    f = open(root)
    line = f.readline()
    locations = []

    while line:
        line = f.readline().strip('\n').split('|')  
        if len(line) == 1:
            break
        locations.append(line[first_column:])
    f.close()
    return locations

In [3]:
root_txt_test = 'ball_predicition_values/testset_labels.txt'
# root_prediction_values = 'ball_predicition_values/bad_imgs.txt'
# root_prediction_values = 'ball_predicition_values/original_imgs.txt'
# root_prediction_values = 'ball_predicition_values/model_3_layer_conv3.txt'
# root_prediction_values = 'ball_predicition_values/model_3_layer_conv5.txt'
# root_prediction_values = 'ball_predicition_values/model_5_layer_conv3.txt'
# root_prediction_values = 'ball_predicition_values/model_5_layer_conv5.txt'
# root_prediction_values = 'ball_predicition_values/model_7_layer_conv5.txt'
root_prediction_values = 'ball_predicition_values/model_9_layer_conv5.txt'




#loading txt_imgs
test_locations = loading_txt(root_txt_test, 5, 0)
test_locations.sort()
prediction_values = loading_txt(root_prediction_values, -1, 0)
prediction_values.sort()

In [4]:
df_locations = pd.DataFrame(test_locations)
df_locations

,0,1,2,3,4,5,6,7,8,9,10
0,img_fr_nov15_000.000.png,800,600,338,164,446,277,392.0,220.5,108,113
1,img_fr_nov15_000.001.png,800,600,498,152,609,262,553.5,207.0,111,110
2,img_fr_nov15_000.003.png,800,600,353,161,508,324,430.5,242.5,155,163
3,img_fr_nov15_000.004.png,800,600,292,166,508,380,400.0,273.0,216,214
4,img_fr_nov15_000.005.png,800,600,528,208,744,420,636.0,314.0,216,212
...,...,...,...,...,...,...,...,...,...,...,...
195,leipzig_robocup16_000.142.png,800,600,121,327,227,441,174.0,384.0,106,114
196,leipzig_robocup16_000.143.png,800,600,62,406,176,504,119.0,455.0,114,98
197,leipzig_robocup16_000.144.png,800,600,133,435,253,546,193.0,490.5,120,111
198,leipzig_robocup16_000.145.png,800,600,264,453,365,555,314.5,504.0,101,102
199,leipzig_robocup16_000.146.png,800,600,360,432,461,529,410.5,480.5,101,97

In [5]:
df_prediction = pd.DataFrame(prediction_values)
df_prediction[0] = df_prediction[0].str.split("/", expand = True).iloc[:,-1]
df_prediction

                                0       1       2      3       4
0    outputs_9_layer_conv5_00.png   399.0   226.0   62.0    0.75
1    outputs_9_layer_conv5_01.png     553     205     58    0.75
2    outputs_9_layer_conv5_02.png     427     232     76   0.875
3    outputs_9_layer_conv5_03.png     395     248     85    0.75
4    outputs_9_layer_conv5_04.png       0       0      0       0
..                            ...     ...     ...    ...     ...
195  outputs_9_layer_conv5_95.png       0       0      0       0
196  outputs_9_layer_conv5_96.png       0       0      0       0
197  outputs_9_layer_conv5_97.png       0       0      0       0
198  outputs_9_layer_conv5_98.png       0       0      0       0
199  outputs_9_layer_conv5_99.png       0       0      0       0

[200 rows x 5 columns]

In [6]:
#sort by name
#Don't sort original images, because the sort is correct
if df_prediction[0][0] != 'img_fr_nov15_000.000.png':     
    df_prediction[0] = df_prediction[0].apply(lambda x : ('img0' + x[-6:-4]) if x[-7] == '_' else ('img'+x[-7:-4]))
    df_prediction = df_prediction.sort_values(by= 0)
    df_prediction = df_prediction.reset_index(drop=True)

In [7]:
#change dtypes
for i in range(1,df_locations.shape[1]):
    df_locations[i] = df_locations[i].astype(np.float32)
for i in range(1,df_prediction.shape[1]):
    df_prediction[i] = df_prediction[i].astype(np.float32)

In [8]:
df_locations.columns = ['filename','img_width','img_height','x1','y1','x2','y2','center_x','center_y','width','height']
df_locations

,filename,img_width,img_height,x1,y1,x2,y2,center_x,center_y,width,height
0,img_fr_nov15_000.000.png,800.0,600.0,338.0,164.0,446.0,277.0,392.0,220.5,108.0,113.0
1,img_fr_nov15_000.001.png,800.0,600.0,498.0,152.0,609.0,262.0,553.5,207.0,111.0,110.0
2,img_fr_nov15_000.003.png,800.0,600.0,353.0,161.0,508.0,324.0,430.5,242.5,155.0,163.0
3,img_fr_nov15_000.004.png,800.0,600.0,292.0,166.0,508.0,380.0,400.0,273.0,216.0,214.0
4,img_fr_nov15_000.005.png,800.0,600.0,528.0,208.0,744.0,420.0,636.0,314.0,216.0,212.0
...,...,...,...,...,...,...,...,...,...,...,...
195,leipzig_robocup16_000.142.png,800.0,600.0,121.0,327.0,227.0,441.0,174.0,384.0,106.0,114.0
196,leipzig_robocup16_000.143.png,800.0,600.0,62.0,406.0,176.0,504.0,119.0,455.0,114.0,98.0
197,leipzig_robocup16_000.144.png,800.0,600.0,133.0,435.0,253.0,546.0,193.0,490.5,120.0,111.0
198,leipzig_robocup16_000.145.png,800.0,600.0,264.0,453.0,365.0,555.0,314.5,504.0,101.0,102.0
199,leipzig_robocup16_000.146.png,800.0,600.0,360.0,432.0,461.0,529.0,410.5,480.5,101.0,97.0

In [9]:
df_merge = pd.merge(df_locations.loc[:, ['filename','center_x','center_y','width']], df_prediction.loc[:, :4], on = df_locations.index)
df_merge.rename(columns={'center_x': 'x','center_y': 'y', 1:'xp', 2:'yp', 3:'rp'}, inplace=True)
df_merge['r'] = df_merge['width']/2
df_merge = df_merge[['filename', 'x', 'y', 'r', 'xp', 'yp', 'rp']]
df_merge

                          filename      x      y      r     xp     yp    rp
0         img_fr_nov15_000.000.png  392.0  220.5   54.0  399.0  226.0  62.0
1         img_fr_nov15_000.001.png  553.5  207.0   55.5  553.0  205.0  58.0
2         img_fr_nov15_000.003.png  430.5  242.5   77.5  427.0  232.0  76.0
3         img_fr_nov15_000.004.png  400.0  273.0  108.0  395.0  248.0  85.0
4         img_fr_nov15_000.005.png  636.0  314.0  108.0    0.0    0.0   0.0
..                             ...    ...    ...    ...    ...    ...   ...
195  leipzig_robocup16_000.142.png  174.0  384.0   53.0  734.0   74.0   9.0
196  leipzig_robocup16_000.143.png  119.0  455.0   57.0    0.0    0.0   0.0
197  leipzig_robocup16_000.144.png  193.0  490.5   60.0  173.0  476.0  29.0
198  leipzig_robocup16_000.145.png  314.5  504.0   50.5    0.0    0.0   0.0
199  leipzig_robocup16_000.146.png  410.5  480.5   50.5  428.0  466.0  25.0

[200 rows x 7 columns]

In [10]:
def calculate_overlap(x):
    dis = x['dis']
    pi = np.arccos(-1.0)
    if (x['r'] + x['rp']) <= dis:
        return 0
    if (x['r'] - x['rp']) >= dis:
        return  pi * x['rp'] * x['rp']
    if (x['rp'] - x['r']) >= dis:
        return  pi * x['r'] * x['r']
    angle1 = np.arccos((x['r'] * x['r'] + dis * dis - x['rp'] * x['rp']) / (2 * dis * x['r']))
    angle2 = np.arccos((x['rp'] * x['rp'] + dis * dis - x['r'] * x['rp']) / (2 * dis * x['rp']))
    return x['r'] * x['r'] * angle1 + x['rp'] * x['rp'] * angle2 - np.sin(angle1) * x['r'] * dis
#     print(x)
# df_merge.iloc[:10, :].apply(calculate_overlap, axis=1)

In [11]:
df_merge['dis'] = np.sqrt(np.square(df_merge['x'] - df_merge['xp']) + np.sqrt(np.square(df_merge['y'] - df_merge['yp'])))
df_merge['overlap_area'] = df_merge.apply(calculate_overlap, axis=1)
df_merge['original_circle_area'] = np.arccos(-1.0) * np.square(df_merge['r'])
df_merge['predicted_circle_area'] = np.arccos(-1.0) * np.square(df_merge['rp'])
acc = ((df_merge['overlap_area']/df_merge['original_circle_area'] > 0.5) & 
 (df_merge['predicted_circle_area']/df_merge['original_circle_area'] < 1.5)).sum()/df_merge.shape[0]

print('acc is: ', acc*100, '%')

acc is:  44.5 %

/Users/yanyu/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in arccos
  # This is added back by InteractiveShellApp.init_path()